# Generated by Django 4.2.4 on 2023-08-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=100)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("CF", "Conference"),
                            ("SM", "Summit"),
                            ("HK", "Hackathon"),
                            ("CJ", "CodeJam"),
                            ("EX", "Expo"),
                            ("SC", "StartupCompetition"),
                            ("DC", "DeveloperConference"),
                            ("WS", "Workshop"),
                            ("MT", "Meetup"),
                            ("UG", "UserGroup"),
                            ("OC", "OnlineConferences"),
                            ("WB", "Webinar"),
                        ],
                        default="",
                        max_length=2,
                    ),
                ),
                ("duration", models.DateTimeField(null=True)),
                ("country", models.CharField(max_length=40, null=True)),
                ("location", models.CharField(max_length=50, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="categories", to="events.category"
                    ),
                ),
            ],
        ),
    ]
